- name: makin users
  collections:
    - "ibm.zvm_ansible"
  hosts: zvmhosts
  tasks:
  - name: add a user
    zvm_user:
      name: thingone
      newpass: AUTOONLY
      prototype: LITMSTC
      exists: true
    register: testout 
  - name: add a user with a prototype that does not exist - should fail
    zvm_user:
      name: baddude
      prototype: ISNTONE
      exists: true
    register: test2out 
    ignore_errors: true
  - name: add a user again idemptotently - "user exists" failure is ignored
    zvm_user:
      name: thingone
      prototype: LITMSTC
      exists: true
    register: test3out 
  - name: resize a user
    zvm_update_user:
      name: thingone
      newpass: letmein
      vcpus: 4
      vcputype: IFL
      maxcpus: 12
      mem: 20
      maxmem: 30
      memsuffix: G
  - name: delete a user
    zvm_user:
      name: thingone
      exists: false
    register: test4out 
- name: making users with dir stubs
  collections:
    - "ibm.zvm_ansible"
  hosts: newlinuxes
  tasks: 
  - name: make dir files
    template:
      src: dirstub.j2
      dest: /tmp/{{ name }}.direct
  - name: add to directory
    zvm_user:
      name: '{{ name }}'
      dirfile: /tmp/{{ name }}.direct
      exists: true
